/*
 *  Cookie Quick Manager: An addon to manage (view, search, create, edit,
 *  remove, backup, restore) cookies on Firefox.
 *  Copyright (C) 2017-2019 Ysard
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Home: https://github.com/ysard/cookie-quick-manager
 */
'use strict';

// IIFE - Immediately Invoked Function Expression
(function(mycode) {

    // The global jQuery object is passed as a parameter
    mycode(window.jQuery, window.vAPI, window, document);

}(function($, vAPI, window, document) {

    // The $ is now locally scoped
    const core = window.CQMCore;
    $(function () {

/*********** Events attached to UI elements ***********/
$("#modal_clipboard").on('shown.bs.modal', function () {
    // Capture the focus on textarea and select all its content
    // Event is triggered when the modal is fully shown (CSS transitions included)
    $('#clipboard_textarea').select();

    try {
        // Copy to clipboard
        // API not available on FF63-
        // This is not an event directly generated by an action of a user,
        // so we have to ask a permission to the user in the manifest.
        // See https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
        navigator.clipboard.writeText($('#clipboard_textarea').val()).then();
    } catch (e) {};
});

/* Bug in FF ? see download().
 $ ("*#file_export").click(function() {
 download($('#domain').val() + ".txt", build_cookie_dump());
});
*/
$("#file_cookie_export").click(function() {
    export_content_to_file(get_concatenated_content(build_cookie_dump()));
});

$("#file_domain_export").click(function() {
    // Build 1 json template for each cookie for the selected domain
    let promise = vAPI.filter_cookies(vAPI.getCookiesFromSelectedDomain());
    promise.then((cookies) => {
        // Make 1 json for each cookie and store it
        // Merge and display templates
        export_content_to_file_wrapper(cookies);

    }, (error) => {
        // No cookie
        console.log({"error:": "No domain selected"});
    });
});

$("#file_all_export").click(function() {
    // Build 1 json template for each cookie in all stores
    let promise = vAPI.filter_cookies(vAPI.get_all_cookies([$('#search_store').val()]));
    promise.then((cookies) => {
        export_content_to_file_wrapper(cookies);
    });
});

$("#clipboard_cookie_export").click(function() {
    // Handle the copy of the current cookie displayed in details zone
    // Build text according to template
    $('#clipboard_textarea').val(get_concatenated_content(build_cookie_dump()));
    // Update title of the dialog box (1 only cookie at the time here)
    $('#modal_clipboard h4.modal-title').text("Export 1 cookie");
    vAPI.ask_permission('clipboardWrite');
});

$("#clipboard_domain_export").click(function() {
    // Build 1 json template for each cookie for the selected domain
    let promise = vAPI.filter_cookies(vAPI.getCookiesFromSelectedDomain());
    display_json_in_clipboard_area(promise);
    vAPI.ask_permission('clipboardWrite');
});

$("#clipboard_all_export").click(function() {
    // Build 1 json template for each cookie in all stores
    let promise = vAPI.filter_cookies(vAPI.get_all_cookies([$('#search_store').val()]));
    display_json_in_clipboard_area(promise);
    vAPI.ask_permission('clipboardWrite');
});

$("#import_file").click(function(event) {
    // Overlay for <input type=file>
    var file_elem = document.getElementById("file_elem");
    if (file_elem) {
        file_elem.click();
    }
    event.preventDefault(); // prevent navigation to "#"
});

$("#file_elem").change(function(event) {
    // File load onto the browser
    var file = event.target.files[0];
    if (!file)
        return;

    var reader = new FileReader();
    reader.onload = function(event) {
        // Restore content
        handleUploadedFile(event.target.result, file.type);
    };
    reader.onerror = function (event) {
        console.error(event.target.error.name);
    };
    reader.readAsText(file);
});

browser.storage.onChanged.addListener(function (changes, area) {
    // Called when the local storage area is modified
    // Here: we handle only 'template' key.

    // Reload template
    if (changes.template !== undefined)
        cookie_clipboard_template = vAPI.templates[changes.template.newValue] || vAPI.template_JSON;
});

/*********** Initializations ***********/

get_options();

});

/*********** Utils ***********/
function get_concatenated_content(templates) {
    // Return string from array of strings
    // According to the current template,
    // make 1 json for each cookie and store it or,
    // return 1 text content with 1 cookie per line.
    return cookie_clipboard_template.left_tag +
        templates.join(cookie_clipboard_template.separator) +
        cookie_clipboard_template.right_tag;
}

function get_templates(cookies) {
    // Return array of templates (strings); 1 for each cookie in the given array
    // Make 1 template for each cookie and store it
    var templates = [];
    for (let cookie of cookies) {
        // Build a template for the current cookie
        templates.push(build_domain_dump(cookie));
    }
    return templates;
}

function export_content_to_file_wrapper(cookies) {
    // Wrapper that chains 3 functions
    // This function is exported to window namespace.
    // Used in contextual Menu (save option),
    // and in click events: #file_domain_export, #file_all_export
    export_content_to_file(get_concatenated_content(get_templates(cookies)));
}

function secure_string(unescaped_string) {
    // Escape double quotes and backslashs only for JSON template
    if (cookie_clipboard_template.name == 'JSON')
        return unescaped_string.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    else if (cookie_clipboard_template.name == 'NETSCAPE')
        return unescaped_string;
    return unescaped_string;
}

function display_json_in_clipboard_area(cookies_promise) {
    // Fill the textarea with the cookies in the given promise
    // This function is exported to window namespace.

    cookies_promise.then((cookies) => {
        // Make 1 json for each cookie
        var templates = get_templates(cookies);
        // Merge and display templates, update title with the number of cookies
        $('#clipboard_textarea').val(get_concatenated_content(templates));
        // Count cookies displayed (not subdomains filtered)
        let title = browser.i18n.getMessage("modalClipboardTitle", String(templates.length));
        $('#modal_clipboard h4.modal-title').text(title);

    }, (error) => {
        // No cookie
        $('#clipboard_textarea').val('');
        $('#modal_clipboard h4.modal-title').text("Export 0 cookie");
    });
}

function build_cookie_dump() {
    // Return the updated template according to the selected cookie in cookie-list,
    // displayed in details.
    // Data: from the User Interface.

    let cookie = {
        domain: $('#domain').val(),
        name: $('#name').val(),
        path: $('#path').val(),
        value: $('#value').val(),
        session: $('#issession').is(':checked'),
        secure: $('#issecure').is(':checked'),
        httpOnly: $('#httponly').is(':checked'),
        sameSite: $('#samesite').val(), // Can be null if not supported
        storeId: $('#store').val(),
        firstPartyDomain: $('#fpi-domain').val(),
    };
    const selectedCookie = $('#cookie-list').find('li.active').data('cookie');
    if (selectedCookie?.partitionKey && selectedCookie.domain === cookie.domain &&
        selectedCookie.name === cookie.name)
        cookie.partitionKey = selectedCookie.partitionKey;

    // If raw is true, return the unix timestamp if the cookie is not a session cookie
    // otherwise, return 0.
    // If raw is false, return human readable date or "At the end of the session" for a
    // session cookie.
    cookie.expirationDate = (!cookie.session) ? $('#expiration_date').data("DateTimePicker").date().unix() : 0;

    // Return the domain status of cookie.
    // If raw is true, return false is cookie is valid for subdomains
    // If raw is false, return "Valid for subdomains" or "Valid for host only".
    // PS:
    //   foo.com => host-only
    //   .foo.com => subdomains
    //   www.foo.com => host-only
    cookie.hostOnly = ($('#domain').val()[0] == '.') ? false : true;

    // Get the updated template according to the given cookie object.
    let template_temp = build_domain_dump(cookie);

    return new Array(template_temp);
    //return JSON.stringify(JSON.parse(template_temp), null, 2);
}

function build_domain_dump(cookie) {
    // Return the updated template according to the given cookie object.
    // Data: from the given cookie object.

    function get_timestamp(raw) {
        // If raw is true, return the unix timestamp if the cookie is not a session cookie
        // otherwise, return 0.
        // If raw is false, return human readable date or "At the end of the session" for a
        // session cookie.
        if (raw) {
            return (!cookie.session) ? cookie.expirationDate : 0;
        }
        return (!cookie.session) ? moment(new Date(cookie.expirationDate * 1000)).format(vAPI.date_format) : "At the end of the session";
    }

    function get_domain_status(raw) {
        // Return the domain status of cookie.
        // If raw is true, return false is cookie is valid for subdomains
        // If raw is false, return "Valid for subdomains" or "Valid for host only".
        // PS:
        //   foo.com => host-only
        //   .foo.com => subdomains
        //   www.foo.com => host-only
        if (raw) {
            // Netscape's include-subdomains column is the inverse of hostOnly.
            return cookie_clipboard_template.name === 'NETSCAPE' ? !cookie.hostOnly : cookie.hostOnly;
        }
        return (cookie.hostOnly) ? "Valid for host only" : "Valid for subdomains";
    }

    function get_secure_status(raw) {
        // Return the secure status of the cookie
        // If raw is true, return true or false
        if (raw) {
            return cookie.secure;
        }
        return (cookie.secure) ? "Encrypted connections only" : "Any type of connection";
    }

    var params = {
        '{HOST_RAW}': core.getCookieUrl(cookie),
        '{DOMAIN_RAW}': cookie.domain,
        '{NAME_RAW}': secure_string(cookie.name),
        '{PATH_RAW}': cookie.path,
        '{CONTENT_RAW}': secure_string(cookie.value),
        '{EXPIRES}': get_timestamp(false),
        '{EXPIRES_RAW}': get_timestamp(true),
        '{ISSECURE}': get_secure_status(false),
        '{ISSECURE_RAW}': get_secure_status(true),
        '{ISHTTPONLY_RAW}': cookie.httpOnly,
        '{SAMESITE_RAW}': cookie.sameSite ? cookie.sameSite : "unspecified",
        '{ISDOMAIN}': get_domain_status(false),
        '{ISDOMAIN_RAW}': get_domain_status(true),
        '{STORE_RAW}': cookie.storeId,
        '{FPI_RAW}': cookie.firstPartyDomain ? cookie.firstPartyDomain : "", // This attr is absent on old FF
    };

    if (cookie_clipboard_template.name === 'JSON') {
        const exportedCookie = {
            'Host raw': params['{HOST_RAW}'],
            'Name raw': cookie.name,
            'Path raw': cookie.path,
            'Content raw': cookie.value,
            'Expires': params['{EXPIRES}'],
            'Expires raw': String(params['{EXPIRES_RAW}']),
            'Send for': params['{ISSECURE}'],
            'Send for raw': String(params['{ISSECURE_RAW}']),
            'HTTP only raw': String(cookie.httpOnly),
            'SameSite raw': cookie.sameSite || 'unspecified',
            'This domain only': params['{ISDOMAIN}'],
            'This domain only raw': String(cookie.hostOnly),
            'Store raw': cookie.storeId,
            'First Party Domain': cookie.firstPartyDomain || '',
        };
        if (cookie.partitionKey)
            exportedCookie['Partition key'] = cookie.partitionKey;
        return JSON.stringify(exportedCookie, null, 2);
    }

    // Make a local copy of the Netscape template.
    var template_temp = cookie_clipboard_template.template;

    // Replace variables in template
    for (let key_pattern in params) {
        // Get rid of $ forms in the replacement string
        // Thx to https://stackoverflow.com/questions/28102491/javascript-better-way-to-escape-dollar-signs-in-the-string-used-by-string-prot
        // http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf
        template_temp = template_temp.replace(key_pattern, function () {return params[key_pattern]});
    }
    return cookie.httpOnly ? `#HttpOnly_${template_temp}` : template_temp;
}

function export_content_to_file(content) {
    // Use an isolated iframe so the manager page is never replaced by the file.

    // Choose the right filename/filetype according to the selected export format
    let cookie_filename;
    let cookie_filetype;
    if (cookie_clipboard_template.name == 'JSON') {
        cookie_filename = 'cookies.json';
        cookie_filetype = 'application/json';
    } else {
        cookie_filename = 'cookies.txt';
        cookie_filetype = 'text/plain';
        content = `# Cookie Quick Manager Netscape v2\n${content}`;
    }

    var f = document.createElement('iframe');
    f.style.position = 'fixed';
    f.style.left = f.style.top = '-99px';
    //f.style.width = f.style.height = '99px';
    f.srcdoc = '<a download="' + cookie_filename + '" target="_blank">' + cookie_filename + '</a>';
    f.onload = function() {
        var blob = new Blob([content], {type: cookie_filetype});
        var a = f.contentDocument.querySelector('a');
        a.href = f.contentWindow.URL.createObjectURL(blob);
        a.click();
        // Removing the frame document implicitly revokes the blob:-URL too.
        setTimeout(function() { f.remove(); }, 2000);
    };
    document.body.appendChild(f);
}

async function handleUploadedFile(content, mimetype) {
    // Take a file content and dispatch it to the good parser
    // Handle errors due to parsers.

    try {
        if (content.length > 10 * 1024 * 1024)
            throw new Error('Import files are limited to 10 MiB.');
        const normalizedContent = content.startsWith('\uFEFF') ? content.slice(1) : content;
        const trimmed = normalizedContent.trimStart();
        const looksLikeJson = trimmed.startsWith('[') || trimmed.startsWith('{');
        let cookieDetails;
        if (mimetype === 'application/json' || looksLikeJson)
            cookieDetails = await parseJSONFile(normalizedContent);
        else if (!mimetype || mimetype === 'text/plain')
            cookieDetails = await parseNETSCAPEFile(normalizedContent);
        else
            throw new Error(`Unsupported file type: ${mimetype}`);
        await add_cookies(cookieDetails);
    } catch (error) {
        set_info_text(browser.i18n.getMessage("cookieRestoredError", String(error?.message || error)));
        $('#modal_info').modal('show');
    }
}

async function parseNETSCAPEFile(content) {
/* Parse Netscape file and return a list of cookies.set promises.
 * NOTE: About default values. The netscape format is less rich than the JSON format,
 * thus some features of the cookies are lost and are replaced by default values when inserting.
 *
 * - sameSite: omitted / browser default.
 * - httpOnly: false (cookie accessible from JS code).
 * - storeId: current selected context.
 * - firstPartyDomain: empty string (No way to know which is the FPI domain).
 *
 * NOTE: About Netscape file format (tabulated only):
 *  0             1               2           3               4              5           6
 * '{DOMAIN_RAW}\t{ISDOMAIN_RAW}\t{PATH_RAW}\t{ISSECURE_RAW}\t{EXPIRES_RAW}\t{NAME_RAW}\t{CONTENT_RAW}'
 */

    await vAPI.FPI_detection();
    const details = [];
    const lines = content.split(/\r?\n/);
    const formatMarker = '# Cookie Quick Manager Netscape v2';
    const versionedCqmFlags = lines.some((candidate) => candidate.trim() === formatMarker);
    const legacyCqmFlags = !versionedCqmFlags && lines.some((candidate) => {
        const fields = candidate.replace(/^#HttpOnly_/, '').split('\t');
        return fields.length === 7 && fields[0].startsWith('.') && !core.parseBoolean(fields[1]);
    });
    let cookieRowCount = 0;
    let expiredCount = 0;
    for (let index = 0; index < lines.length; index++) {
        let rawLine = lines[index];
        if (!rawLine.trim())
            continue;
        let httpOnly = false;
        if (rawLine.startsWith('#HttpOnly_')) {
            httpOnly = true;
            rawLine = rawLine.slice('#HttpOnly_'.length);
        } else if (rawLine.startsWith('#')) {
            continue;
        }

        const line = rawLine.split('\t');
        if (line.length !== 7)
            throw new Error(`Invalid Netscape cookie at line ${index + 1}.`);
        cookieRowCount++;
        if (cookieRowCount > 10000)
            throw new RangeError('A single import is limited to 10,000 cookies.');
        const expirationDate = Number.parseInt(line[4], 10);
        if (!Number.isFinite(expirationDate))
            throw new Error(`Invalid expiration date at line ${index + 1}.`);
        if (expirationDate !== 0 && expirationDate <= ((Date.now() / 1000 | 0) + 1)) {
            expiredCount++;
            continue;
        }

        const cookie = {
            domain: line[0],
            hostOnly: line[0].startsWith('.') ? false :
                (legacyCqmFlags ? core.parseBoolean(line[1], true) : !core.parseBoolean(line[1])),
            path: line[2],
            secure: core.parseBoolean(line[3]),
            httpOnly,
            name: line[5],
            value: line[6],
            session: expirationDate === 0,
        };
        if (!cookie.session)
            cookie.expirationDate = expirationDate;
        if ($('#search_store').val() !== 'all')
            cookie.storeId = $('#search_store').val();
        if (vAPI.FPI !== undefined)
            cookie.firstPartyDomain = '';
        details.push(core.buildCookieSetDetails(cookie));
    }
    details.expiredCount = expiredCount;
    return details;
}

async function parseJSONFile(content) {
    // Parse JSON file and return a list of cookies.set promises.

    const parsed = JSON.parse(content);
    const jsonCookies = Array.isArray(parsed) ? parsed :
        (parsed && parsed.format === 'cookie-quick-manager' && Array.isArray(parsed.cookies) ? parsed.cookies : null);
    if (!jsonCookies)
        throw new TypeError('Cookie JSON must be an array or a Cookie Quick Manager export object.');
    if (jsonCookies.length > 10000)
        throw new RangeError('A single import is limited to 10,000 cookies.');

    await vAPI.FPI_detection();
    const defaultStoreId = $('#search_store').val() !== 'all' ?
        $('#search_store').val() : vAPI.currentContextStoreId();
    const detailsList = [];
    let expiredCount = 0;
    for (const record of jsonCookies) {
        try {
            const details = core.parseJsonCookieRecord(record, {
                defaultStoreId,
                supportsFirstPartyIsolation: vAPI.FPI !== undefined,
            });
            if (details.storeId && vAPI.storeIds.length && !vAPI.storeIds.includes(details.storeId))
                details.storeId = defaultStoreId;
            detailsList.push(details);
        } catch (error) {
            if (error?.code === 'EXPIRED') {
                expiredCount++;
                continue;
            }
            throw error;
        }
    }
    detailsList.expiredCount = expiredCount;
    return detailsList;
}

async function add_cookies(cookieDetails) {
    // Take a list of cookie.set promises and execute them
    // Cookies are protected on the fly according to the option "Protect cookies during import"
    // Handle errors due to the insertion of cookies.

    const items = await browser.storage.local.get({import_protected_cookies: false});
    const results = [];
    for (let index = 0; index < cookieDetails.length; index += 50) {
        const batch = cookieDetails.slice(index, index + 50);
        results.push(...await Promise.allSettled(batch.map((details) => vAPI.set_cookie(details))));
    }
    const addedCookies = results
        .filter((result) => result.status === 'fulfilled' && result.value)
        .map((result) => result.value);
    const failedCount = results.length - addedCookies.length;
    if (items.import_protected_cookies && addedCookies.length) {
        try {
            await vAPI.set_cookie_protection(addedCookies, true);
        } catch (error) {
            // Import succeeded; a follow-up protection failure must not be
            // presented as though the cookies themselves were not restored.
            console.error('Failed to protect imported cookies:', error);
        }
    }

    const expiredCount = Number(cookieDetails.expiredCount) || 0;
    const messages = [];
    if (addedCookies.length)
        messages.push(browser.i18n.getMessage('cookieRestoredSuccess', String(addedCookies.length)));
    if (failedCount)
        messages.push(browser.i18n.getMessage('cookieRestoredSingleError', String(failedCount)));
    if (expiredCount)
        messages.push(browser.i18n.getMessage('cookieRestoredExpiredSkipped', String(expiredCount)));
    if (!messages.length) {
        const successMessage = browser.i18n.getMessage('cookieRestoredSuccess', String(addedCookies.length));
        messages.push(successMessage);
    }
    set_info_text(messages.join('<br>'));
    $('#actualize_button').click();
    $('#modal_info').modal('show');
    return {added: addedCookies.length, failed: failedCount, expired: expiredCount};
}

function set_info_text(content) {
    const infoText = document.getElementById('info_text');
    infoText.replaceChildren();
    const chunks = String(content).split(/<br\s*\/?\s*>/i);
    chunks.forEach((chunk, index) => {
        if (index)
            infoText.appendChild(document.createElement('br'));
        infoText.appendChild(document.createTextNode(chunk));
    });
}

function get_options() {
    // Get options from storage
    // Init cookie_clipboard_template array in global context

    let get_settings = browser.storage.local.get({
        template: 'JSON',
    });
    get_settings.then((items) => {
        //console.log({storage_data: items});
        cookie_clipboard_template = vAPI.templates[items.template];
    });
}


var cookie_clipboard_template;

window.display_json_in_clipboard_area = display_json_in_clipboard_area;
window.export_content_to_file_wrapper = export_content_to_file_wrapper;
}));
